import click
import os
import shutil
import subprocess
from src.utils import complete_env_vars
from src.utils import ENV_DIR
from src.cli import envm


@envm.command()
@click.option('--envfile', default=".env", help='Name of the file to be saved')
@click.option('--overwrite/--no-overwrite', default=False, help='Overwrite env name')
@click.option('--direnv', is_flag=True, help='Generate .envrc file for direnv integration')
@click.argument('name', shell_complete=complete_env_vars)
def use(envfile, name, overwrite, direnv):
    """Use the environment file in the current path.
    Default write as .env file
    """
    path = f"{ENV_DIR}/{name}"

    if not os.path.exists(path) or not os.path.isfile(path):
        click.secho(f"{name} environment is not saved", blink=True, bold=True, fg="red")
        return

    if direnv:
        create_envrc_file(path, name, overwrite)
    else:
        if os.path.exists(f"{envfile}") and not overwrite:
            click.confirm(f"{envfile} file actually exists in the current directory. Do you want to override?", abort=True)

        shutil.copyfile(path, f"{envfile}")
        click.secho(f"{name} written as {envfile}", fg="green")


def check_direnv_installation():
    """Check if direnv is installed and provide installation instructions if not"""
    if shutil.which('direnv') is None:
        click.secho("❌ direnv is not installed.", fg="red", bold=True)
        click.echo("\n📦 Install direnv first:")
        click.secho("  Ubuntu/Debian: ", nl=False, fg="cyan")
        click.echo("sudo apt install direnv")
        click.secho("  macOS: ", nl=False, fg="cyan")
        click.echo("brew install direnv")
        click.secho("  Other systems: ", nl=False, fg="cyan")
        click.echo("https://direnv.net/docs/installation.html")
        
        shell = os.environ.get('SHELL', '').split('/')[-1]
        click.echo(f"\n🔧 Then add the hook to your shell configuration:")
        
        # Show the 3 most popular shells
        click.secho("  BASH: ", nl=False, fg="green", bold=True)
        click.echo("Add to ~/.bashrc")
        click.secho('    eval "$(direnv hook bash)"', fg="yellow")
        
        click.secho("  ZSH: ", nl=False, fg="green", bold=True)
        click.echo("Add to ~/.zshrc")
        click.secho('    eval "$(direnv hook zsh)"', fg="yellow")
        
        click.secho("  FISH: ", nl=False, fg="green", bold=True)
        click.echo("Add to ~/.config/fish/config.fish")
        click.secho('    direnv hook fish | source', fg="yellow")
        
        click.echo("\n💡 Restart your terminal after setup.")
        click.secho("📖 More shells: https://direnv.net/docs/hook.html", fg="blue")
        return False
    return True


def is_direnv_allowed():
    """Check if direnv allow has been run for the current directory"""
    try:
        result = subprocess.run(['direnv', 'status'], 
                              capture_output=True, 
                              text=True, 
                              cwd=os.getcwd())
        
        if result.returncode == 0:
            # Check if the current directory is in the allowed list
            # direnv status shows "Found RC allowed true" for allowed directories
            return "Found RC allowed true" in result.stdout
        return False
    except Exception:
        return False


def create_envrc_file(env_path, env_name, overwrite):
    """Generate .envrc file for direnv and auto-allow if requested"""
    
    # Check if direnv is installed
    if not check_direnv_installation():
        return
    
    # Check if .envrc already exists
    if os.path.exists('.envrc') and not overwrite:
        click.confirm('📄 .envrc already exists in current directory. Override?', abort=True)
    
    # Generate .envrc content
    envrc_content = f"""# Generated by envm for environment: {env_name}
# This file is managed by envm - do not edit manually

"""
    
    # Read environment file and convert to exports
    try:
        with open(env_path, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    envrc_content += f"export {line}\n"
    except Exception as e:
        click.secho(f"❌ Error reading environment file: {e}", fg="red")
        return
    
    # Write .envrc file
    try:
        with open('.envrc', 'w') as f:
            f.write(envrc_content)
        click.secho(f"✅ Generated .envrc for {env_name}", fg="green", bold=True)
    except Exception as e:
        click.secho(f"❌ Error creating .envrc: {e}", fg="red")
        return
    
    # Check if direnv allow has already been run
    if is_direnv_allowed():
        click.secho("✅ direnv is already allowed for this directory", fg="green", bold=True)
        click.secho("🎉 Environment variables are now automatically loaded!", fg="cyan")
        return
    
    # Ask user if they want to auto-allow
    if click.confirm("🚀 Would you like to automatically run 'direnv allow' now?", default=True):
        try:
            result = subprocess.run(['direnv', 'allow'], 
                                  capture_output=True, 
                                  text=True, 
                                  cwd=os.getcwd())
            
            if result.returncode == 0:
                click.secho("✅ direnv allow executed successfully!", fg="green", bold=True)
                click.secho("🎉 Environment variables are now automatically loaded in this directory!", fg="cyan")
            else:
                click.secho(f"❌ Error running direnv allow: {result.stderr}", fg="red")
                click.secho("💡 Run 'direnv allow' manually to activate", fg="yellow")
        except Exception as e:
            click.secho(f"❌ Error executing direnv allow: {e}", fg="red")
            click.secho("💡 Run 'direnv allow' manually to activate", fg="yellow")
    else:
        click.secho("💡 Remember to run 'direnv allow' to activate the environment", fg="yellow")
